//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuitWeb.Resources.Models {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedLocalizer_es_ES {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedLocalizer_es_ES() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DocuitWeb.Resources.Models.SharedLocalizer.es-ES", typeof(SharedLocalizer_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MSG001 {
            get {
                return ResourceManager.GetString("MSG001", resourceCulture);
            }
        }
        
        internal static string MSG002 {
            get {
                return ResourceManager.GetString("MSG002", resourceCulture);
            }
        }
        
        internal static string MSG003 {
            get {
                return ResourceManager.GetString("MSG003", resourceCulture);
            }
        }
        
        internal static string MSG004 {
            get {
                return ResourceManager.GetString("MSG004", resourceCulture);
            }
        }
        
        internal static string MSG005 {
            get {
                return ResourceManager.GetString("MSG005", resourceCulture);
            }
        }
        
        internal static string MSG006 {
            get {
                return ResourceManager.GetString("MSG006", resourceCulture);
            }
        }
        
        internal static string MSG007 {
            get {
                return ResourceManager.GetString("MSG007", resourceCulture);
            }
        }
        
        internal static string MSG100 {
            get {
                return ResourceManager.GetString("MSG100", resourceCulture);
            }
        }
        
        internal static string MSG101 {
            get {
                return ResourceManager.GetString("MSG101", resourceCulture);
            }
        }
        
        internal static string MSG102 {
            get {
                return ResourceManager.GetString("MSG102", resourceCulture);
            }
        }
        
        internal static string MSG103 {
            get {
                return ResourceManager.GetString("MSG103", resourceCulture);
            }
        }
        
        internal static string MSG104 {
            get {
                return ResourceManager.GetString("MSG104", resourceCulture);
            }
        }
        
        internal static string MSG105 {
            get {
                return ResourceManager.GetString("MSG105", resourceCulture);
            }
        }
        
        internal static string MSG106 {
            get {
                return ResourceManager.GetString("MSG106", resourceCulture);
            }
        }
        
        internal static string MSG107 {
            get {
                return ResourceManager.GetString("MSG107", resourceCulture);
            }
        }
        
        internal static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        internal static string MSG_CANCEL {
            get {
                return ResourceManager.GetString("MSG_CANCEL", resourceCulture);
            }
        }
        
        internal static string MSG_DELETE {
            get {
                return ResourceManager.GetString("MSG_DELETE", resourceCulture);
            }
        }
        
        internal static string MSG_EDIT {
            get {
                return ResourceManager.GetString("MSG_EDIT", resourceCulture);
            }
        }
        
        internal static string MSG_ADD {
            get {
                return ResourceManager.GetString("MSG_ADD", resourceCulture);
            }
        }
        
        internal static string MSG_SAVE {
            get {
                return ResourceManager.GetString("MSG_SAVE", resourceCulture);
            }
        }
        
        internal static string OP_OK_TITLE {
            get {
                return ResourceManager.GetString("OP_OK_TITLE", resourceCulture);
            }
        }
        
        internal static string OP_OK {
            get {
                return ResourceManager.GetString("OP_OK", resourceCulture);
            }
        }
        
        internal static string OP_FAIL_TITLE {
            get {
                return ResourceManager.GetString("OP_FAIL_TITLE", resourceCulture);
            }
        }
        
        internal static string OP_FAIL {
            get {
                return ResourceManager.GetString("OP_FAIL", resourceCulture);
            }
        }
        
        internal static string OP_WARNING_TITLE {
            get {
                return ResourceManager.GetString("OP_WARNING_TITLE", resourceCulture);
            }
        }
        
        internal static string OP_WARNING {
            get {
                return ResourceManager.GetString("OP_WARNING", resourceCulture);
            }
        }
        
        internal static string OP_PROCESS_RUNNING {
            get {
                return ResourceManager.GetString("OP_PROCESS_RUNNING", resourceCulture);
            }
        }
        
        internal static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        internal static string LOGIN_TITLE_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_TITLE_ERROR", resourceCulture);
            }
        }
        
        internal static string LOGIN_CREDENTIALS_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_CREDENTIALS_ERROR", resourceCulture);
            }
        }
        
        internal static string LOGIN_NOT_LOGGED {
            get {
                return ResourceManager.GetString("LOGIN_NOT_LOGGED", resourceCulture);
            }
        }
        
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        internal static string LOGIN_PROFILE {
            get {
                return ResourceManager.GetString("LOGIN_PROFILE", resourceCulture);
            }
        }
        
        internal static string ADDRESS_WRONG {
            get {
                return ResourceManager.GetString("ADDRESS_WRONG", resourceCulture);
            }
        }
    }
}
